env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  no-console: 0
  import/extensions: 0
  react/jsx-indent: 'warn'
  react/prop-types: 'warn'
  react/no-array-index-key: 'warn'
  react/jsx-props-no-spreading: 'warn'
  react/destructuring-assignment: 'warn'
  react/jsx-one-expression-per-line: 'warn'
  no-param-reassign: 'warn'
  no-unused-vars: 'warn'
  no-shadow: 'warn'
  max-len: 'warn'
  no-await-in-loop: 'warn'
  no-unused-expressions: 'warn'
  no-return-assign: 'warn'
  no-confusing-arrow: 'warn'
  no-underscore-dangle: 'warn'
  no-undef: 'warn'
  object-curly-newline: 'warn'
  no-trailing-spaces: 'warn'
  no-multi-spaces: 'warn'
